services:
  bambulanviewer:
    build: .
    container_name: BambuLanViewer
    restart: unless-stopped
    networks:
      - virtual-network
    ports:
      - "8080:8080"
    environment:
      - BambuMqttClient__IPAddress=192.168.1.*
      - BambuMqttClient__AccessCode=****
      - BambuMqttClient__SerialNumber=****
networks:
  virtual-network:
    external: true
    name: virtual-network