services:
  foodtrax:
    build: .
    # image: localhost:5000/foodtrax:latest
    container_name: BambuLanViewer
    restart: unless-stopped
    networks:
      - virtual-network
    labels:
      dmz.url: http://bambulanviewer.docker.local/
    ports:
      - "8080:8080"

networks:
  virtual-network:
    external: true
    name: virtual-network